stages:
  - build
  - deploy
  - test
  - rollback

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: ['']
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE:latest
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
  only:
    - main

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add curl
  script:
    - 'curl --cacert $LNU_CA_CERT -f -X POST $WEBHOOK_URL -H "X-Gitlab-Token: $WEBHOOK_TOKEN"'
  only:
    - main

smoke-test:
  stage: test
  image: node:22-alpine
  before_script:
    - npm install -g @usebruno/cli
  script:
    - echo "Waiting 30s for container to start up..."
    - sleep 30
    - NODE_EXTRA_CA_CERTS=$LNU_CA_CERT bru run --env-var baseUrl=https://cu1114.camp.lnu.se --sandbox=developer
  only:
    - main

rollback:
  stage: rollback
  image: alpine
  needs:
    - job: smoke-test
  before_script:
    - apk add curl
  script:
    - 'curl --cacert $LNU_CA_CERT -f -X POST $ROLLBACK_WEBHOOK_URL -H "X-Gitlab-Token: $WEBHOOK_TOKEN"'
  when: on_failure
  only:
    - main
